"""Initialize utils package."""

from src.utils.exceptions import (
    DeepAIException,
    SecurityException,
    ValidationException,
    DomainBlockedException,
    RateLimitException,
    TimeoutException,
    HoneypotDetectedException,
    DataCollectionException,
    FeatureExtractionException,
    ModelException,
    ExplainabilityException,
    AuditLogException,
    AcademicModeViolationException,
)
from src.utils.helpers import (
    is_valid_domain_format,
    is_private_ip,
    extract_base_domain,
    get_tld,
    calculate_hash,
    normalize_domain,
    is_valid_url,
    extract_domain_from_url,
    safe_json_dumps,
    calculate_gini_coefficient,
    AttributeDict,
)
from src.utils.constants import (
    RISK_LEVELS,
    RISK_LEVEL_SCORES,
    RL_ACTIONS,
    TIMEOUT_TOTAL_SCAN,
    TIMEOUT_HTTP,
    TLS_VERSIONS,
    COMMON_PORTS,
    DATABASE_PORTS,
    ADMIN_PATHS,
)

__all__ = [
    # Exceptions
    "DeepAIException",
    "SecurityException",
    "ValidationException",
    "DomainBlockedException",
    "RateLimitException",
    "TimeoutException",
    "HoneypotDetectedException",
    "DataCollectionException",
    "FeatureExtractionException",
    "ModelException",
    "ExplainabilityException",
    "AuditLogException",
    "AcademicModeViolationException",
    # Helpers
    "is_valid_domain_format",
    "is_private_ip",
    "extract_base_domain",
    "get_tld",
    "calculate_hash",
    "normalize_domain",
    "is_valid_url",
    "extract_domain_from_url",
    "safe_json_dumps",
    "calculate_gini_coefficient",
    "AttributeDict",
    # Constants
    "RISK_LEVELS",
    "RISK_LEVEL_SCORES",
    "RL_ACTIONS",
    "TIMEOUT_TOTAL_SCAN",
    "TIMEOUT_HTTP",
    "TLS_VERSIONS",
    "COMMON_PORTS",
    "DATABASE_PORTS",
    "ADMIN_PATHS",
]
